[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "antipetros_discordbot"
author = "antistasi_tools"
home-page = "https://github.com/Giddius/Antipetros_Discord_Bot"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires = [
    "WeasyPrint>=52.2",
    "pdfkit>=0.6.1",
    "googletrans>=4.0.0rc1",
    "pytz>=2020.4",
    "watchgod>=0.6",
    "aiohttp>=3.6.3",
    "google_auth_oauthlib>=0.4.2",
    "async_property>=0.2.1",
    "fuzzywuzzy>=0.18.0",
    "dpytest>=0.0.22",
    "Jinja2>=2.11.2",
    "discord>=1.0.1",
    "gidappdata>=0.1.1",
    "gidlogger>=0.1.3",
    "google_api_python_client>=1.12.8",
    "Pillow>=8.0.1",
    "protobuf>=3.14.0",
    "PyQt5>=5.15.2",
    "python-dotenv>=0.15.0",
]

[tool.flit.scripts]
